language: python
dist: xenial
sudo: false
python: 2.7

# 3.7 needs xenial and sudo https://github.com/travis-ci/travis-ci/issues/9815
# This enables 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=py27
    - python: 3.5
      env:
        - TOXENV=py35
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 3.7
      env:
        - TOXENV=py37
    - python: "3.8-dev"
      env:
       - TOXENV=py38
    - python: 3.7
      env:
        - TOXENV=lint
  allow_failures:
    - python: "3.8-dev"

install:
  - pip install tox

script:
  - tox -e $TOXENV

after_success:
  - pip install codecov
  - codecov
